server {
    listen 80;
    server_name __APP_URL__;
    
    client_max_body_size 100M;
    client_body_buffer_size 128k;

    location / {
        proxy_pass http://rag-web:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        
        proxy_redirect off;
    }
}

# Server Khusus untuk API Subdomain
server {
    listen 80;
    server_name __API_URL__;

    # Berikan pengecualian akses (tanpa token) khusus untuk Web Dokumentasi API (Swagger/ReDoc)
    location ~ ^/(docs|redoc|openapi\.json)$ {
        proxy_pass http://rag-api:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }

    location / {
        # --- API GATEWAY SECURITY ---
        if ($http_authorization !~* "^Bearer __API_SECRET_KEY__\s*$") {
            return 401 "{\"error\": \"Unauthorized: Missing or invalid Bearer Token\"}";
        }
        
        # Opsi tambahan agar Nginx memberikan tipe konten JSON jika error
        default_type application/json;

        proxy_pass http://rag-api:5001/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        
        # Beri kelonggaran waktu tunda (timeout) hingga 5 menit untuk AI memuat
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
    }
}
